name: cmgan_pesq_const
d: { slope: 0.0, icpt: 0.0824, min: -0.1, max: 0.5, log: false }
s: { slope: 0.0, icpt: 0.9933, min: 0.0, max: 1.5, log: false }
a: { slope: 0.0, icpt: 2.4248, min: 0.1, max: 100.0, log: true }
